Othello Solver: solver.c File Reference
solver.c File Reference
#include <ctype.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
Data Structures
struct Move
struct SquareList
struct MoveList
struct Board
struct Hash
struct HashEntry
struct HashTable
Macros
#define EMPTIES_DEEP_TO_SHALLOW_SEARCH 7
#define USE_HASH_TABLE 1
#define USE_ENHANCED_TRANSPOSITION_CUTOFF (1 && USE_HASH_TABLE)
#define PLAY_ODD_SQUARE_FIRST 1
#define PLAY_FAST_SUBTREE_FIRST 1
#define PLAY_STABLEST_SUBTREE (1 && PLAY_FAST_SUBTREE_FIRST)
#define PLAY_BEST_MOVE_IN_MEMORY_FIRST (1 && USE_HASH_TABLE)
#define USE_PRESORTED_SQUARES 1
#define COUNT_NODES 3
#define INF_SCORE 127
#define BOARD_SIZE 91
#define MAX_MOVE 32
#define MAX_FLIP 20
#define MAX_SCORE 64
#define BOARD_UPDATE_INTERNAL_NODES() board->n_nodes++;
#define BOARD_UPDATE_TERMINAL_NODES() board->n_nodes++;
#define BOARD_CORRECT_TERMINAL_NODES() board->n_nodes--;
#define BOARD_UPDATE_ALL_NODES() board->n_nodes++
#define BOARD_CHECK_MOVE_6(dir)
#define BOARD_CHECK_MOVE_4(dir)
#define BOARD_COUNT_FLIPS_6(dir)
#define BOARD_COUNT_FLIPS_4(dir)
#define BOARD_FLIP(dir, max_flip)
#define BOARD_GET_MOVE(dir, max_flip)
#define BOARD_UPDATE_SQUARE(board, move)
#define BOARD_RESTORE_SQUARE(board, move)
#define BOARD_UPDATE_PLAYER(board) (board->player = o)
#define BOARD_RESTORE_PLAYER(board) (board->player = p)
#define BOARD_UPDATE_DISCS(board, n_flips)
#define BOARD_RESTORE_DISCS(board, n_flips)
#define BOARD_UPDATE_PARITY(board, x) (board->parity[QUADRANT_ID[x]] ^= 1)
#define BOARD_RESTORE_PARITY(board, x) (board->parity[QUADRANT_ID[x]] ^= 1)
#define BOARD_UPDATE_EMPTIES(board, empties, x)
#define BOARD_RESTORE_EMPTIES(board, empties, x)
#define BOARD_LAST_UPDATE_EMPTIES(board, empties, x)
#define BOARD_LAST_RESTORE_EMPTIES(board, empties, x)
#define BOARD_UPDATE_HASH_CODE(board, code)
#define BOARD_RESTORE_HASH_CODE(board, code)
#define OPPONENT(p) ((p) ^ 1)
#define HASH_TABLE_OK(hash_table) (hash_table->hash_mask != 0)
#define TICK_TO_H(t) (int)((t) / 3600 / CLOCKS_PER_SEC)
#define TICK_TO_M(t) (int)(((t) / 60 / CLOCKS_PER_SEC) % 60)
#define TICK_TO_S(t) (int)(((t) / CLOCKS_PER_SEC) % 60)
#define TICK_TO_DS(t) (int)(((t) / (CLOCKS_PER_SEC / 10)) % 10)
Typedefs
typedef struct Move Move
typedef struct SquareList SquareList
typedef struct MoveList MoveList
typedef struct Board Board
typedef struct Hash Hash
typedef struct HashEntry HashEntry
typedef struct HashTable HashTable
Enumerations
enum {
NOMOVE = 0 , PASS , A1 = 10 , B1 ,
C1 , D1 , E1 , F1 ,
G1 , H1 , A2 = 19 , B2 ,
C2 , D2 , E2 , F2 ,
G2 , H2 , A3 = 28 , B3 ,
C3 , D3 , E3 , F3 ,
G3 , H3 , A4 = 37 , B4 ,
C4 , D4 , E4 , F4 ,
G4 , H4 , A5 = 46 , B5 ,
C5 , D5 , E5 , F5 ,
G5 , H5 , A6 = 55 , B6 ,
C6 , D6 , E6 , F6 ,
G6 , H6 , A7 = 64 , B7 ,
C7 , D7 , E7 , F7 ,
G7 , H7 , A8 = 73 , B8 ,
C8 , D8 , E8 , F8 ,
G8 , H8
}
enum {
NW = -10 , N = -9 , NE = -8 , W = -1 ,
E = +1 , SW = +8 , S = +9 , SE = +10
}
enum { BLACK = 0 , WHITE , EMPTY , OFF_SIDE }
enum { EXACT_SCORE , WDL_SCORE , WD_SCORE , DL_SCORE }
Functions
unsigned long hash_random (void)
Pseudo-random number generator.
void hash_init (HashTable *hash_table, int n_bits)
Initialise the hashtable.
void hash_clear (HashTable *hash_table)
Clear the hashtable.
void hash_free (HashTable *hash_table)
Free the hashtable.
void hash_update (HashTable *hash_table, const Board *board, int alpha, int beta, int score, int move)
Update an hashtable entry.
Hash * hash_get (HashTable *hash_table, const Board *board)
Find an hash table entry according to the evaluated board hash codes.
void board_set (Board *board, const char *string)
Set a board from a string description.
int board_check_move (const Board *board, int x, int player)
Check move validity.
int board_count_flips (Board *board, int x, const char p)
Count flipped on the board.
int board_do_flip (Board *board, int x, Move *move)
Flip discs on the board.
int board_get_move (const Board *board, int x, Move *move)
Compute a move.
void board_update_move (Board *board, const Move *move)
Update a board.
void board_restore_move (Board *board, const Move *move)
Restore a board.
void board_update_pass (Board *board)
Passing move.
void board_restore_pass (Board *board)
Un-passing.
void board_get_movelist (const Board *board, MoveList *start)
Get a list of legal moves.
int board_get_mobility (const Board *board, int player)
Estimate the mobility.
int board_get_corner_stability (Board *board, int player)
Estimate corner stability.
void board_print (Board *board, FILE *f)
Initialize the local parity counters.
void move_print (int x, int player, FILE *f)
Print out a move.
void line_print (Board *board, HashTable *hash_table, int depth, FILE *f)
Print a PV.
void movelist_sort_bestmove (MoveList *movelist, int move)
Sort a move as best.
void movelist_sort_fastfirst (MoveList *movelist, Board *board)
Sort a list of move, fastest-first.
int board_get_final_score (const Board *board)
Get the final score.
int board_get_final_score_0 (const Board *board)
Get the final score.
int board_get_final_score_1 (Board *board)
Get the final score.
int board_get_final_score_2 (Board *board, int alpha, int beta, int passed)
Get the final score.
int alphabeta_shallow (Board *board, int alpha, int beta, int passed)
Evaluate a position using a shallow Alphabeta.
int PVS_deep (Board *board, HashTable *hash_table, int alpha, int beta, int passed)
Evaluate a position with a deep Principal Variation Search algorithm.
void PVS_root (Board *board, HashTable *hash_table, int alpha, int beta, int depth, MoveList *movelist)
Principal Variation Search algorithm at the root of the tree.
void solve (Board *board, HashTable *hash_table, int depth, Move *bestmove)
Search the bestmove of a given board.
void usage (void)
Print program usage.
int main (int argc, char **argv)
Program main function.
Variables
const int FLIPPING_DIRECTION_ID [BOARD_SIZE]
const int QUADRANT_ID [BOARD_SIZE]
Macro Definition Documentation
BOARD_CHECK_MOVE_4
#define BOARD_CHECK_MOVE_4 (dir)
Value:
    ( square[dir] == o &&                               \
    ( square[2 * dir] == p || (square[2 * dir] == o &&  \
    ( square[3 * dir] == p || (square[3 * dir] == o &&  \
    ( square[4 * dir] == p || (square[4 * dir] == o &&  \
      square[5 * dir] == p)))))))
macros to check if a move (<= 4 flips) is correct along a direction
BOARD_CHECK_MOVE_6
#define BOARD_CHECK_MOVE_6 (dir)
Value:
    ( square[dir] == o &&                               \
    ( square[2 * dir] == p || (square[2 * dir] == o &&  \
    ( square[3 * dir] == p || (square[3 * dir] == o &&  \
    ( square[4 * dir] == p || (square[4 * dir] == o &&  \
    ( square[5 * dir] == p || (square[5 * dir] == o &&  \
    ( square[6 * dir] == p || (square[6 * dir] == o &&  \
      square[7 * dir] == p)))))))))))
macros to check if a move (<= 6 flips) is correct along a direction
BOARD_CORRECT_TERMINAL_NODES
#define BOARD_CORRECT_TERMINAL_NODES () board->n_nodes--;
node counter correction for terminal nodes
BOARD_COUNT_FLIPS_4
#define BOARD_COUNT_FLIPS_4 (dir)
Value:
    if (square[dir] == o) {                                     \
        if (square[2 * dir] == p) n_flips++;                    \
        else if (square[2 * dir] == o) {                        \
            if (square[3 * dir] == p) n_flips += 2;             \
            else if (square[3 * dir] == o) {                    \
                if (square[4 * dir] == p) n_flips += 3;         \
                else if (square[4 * dir] == o                   \
                         && square[5 * dir] == p) n_flips += 4; \
    }}}
macro to count (at most 4) discs flipped along a direction
BOARD_COUNT_FLIPS_6
#define BOARD_COUNT_FLIPS_6 (dir)
Value:
    if (square[dir] == o) {                                          \
        if (square[2 * dir] == p) n_flips++;                         \
        else if (square[2 * dir] == o) {                             \
            if (square[3 * dir] == p) n_flips += 2;                  \
            else if (square[3 * dir] == o) {                         \
                if (square[4 * dir] == p) n_flips += 3;              \
                else if (square[4 * dir] == o) {                     \
                        if (square[5 * dir] == p) n_flips += 4;      \
                        else if (square[5 * dir] == o) {             \
                            if (square[6 * dir] == p) n_flips += 5;  \
                            else if (square[6 * dir] == o            \
                             && square[7 * dir] == p) n_flips += 6;  \
    }}}}}
macro to count (at most 6) discs flipped along a direction
BOARD_FLIP
#define BOARD_FLIP (dir, max_flip)
Value:
    if (BOARD_CHECK_MOVE_##max_flip(dir)) { \
        int z = x + (dir);                  \
        do {                                \
            board->square[z] = p;           \
            move->position[++move->n] = z;  \
            z += (dir);                     \
        } while (board->square[z] == o);    \
    }
macro to flip discs along a direction
BOARD_GET_MOVE
#define BOARD_GET_MOVE (dir, max_flip)
Value:
    if (BOARD_CHECK_MOVE_##max_flip(dir)) {                  \
        int z = x + (dir);                                   \
        do {                                                 \
            move->position[++move->n] = z;                   \
            move->hash_code[0] ^= hash_code_flip_disc[z][0]; \
            move->hash_code[1] ^= hash_code_flip_disc[z][1]; \
            z += (dir);                                      \
        } while (board->square[z] == o);                     \
    }
macro to get a move along a direction
BOARD_LAST_RESTORE_EMPTIES
#define BOARD_LAST_RESTORE_EMPTIES (board, empties, x)
Value:
    empties = board->position_to_empties[x];          \
    empties->previous->next = empties;
macro to restore for the last time the list of empty squares
BOARD_LAST_UPDATE_EMPTIES
#define BOARD_LAST_UPDATE_EMPTIES (board, empties, x)
Value:
    empties = board->position_to_empties[x];         \
    empties->previous->next = empties->next;
macro to update for the last time the list of empty squares
BOARD_RESTORE_DISCS
#define BOARD_RESTORE_DISCS (board, n_flips)
Value:
    board->n_discs[(int)p] -= n_flips + 1;      \
    board->n_discs[(int)o] += n_flips;          \
    board->n_empties++;
BOARD_RESTORE_EMPTIES
#define BOARD_RESTORE_EMPTIES (board, empties, x)
Value:
    empties = board->position_to_empties[x];     \
    empties->previous->next = empties;           \
    empties->next->previous = empties;
macro to restore the list of empty squares
BOARD_RESTORE_HASH_CODE
#define BOARD_RESTORE_HASH_CODE (board, code)
Value:
    board->hash_code[0] ^= code[0];          \
    board->hash_code[1] ^= code[1];
macro to restore the hash codes
BOARD_RESTORE_PARITY
#define BOARD_RESTORE_PARITY (board, x) (board->parity[QUADRANT_ID[x]] ^= 1)
macro to restore parity
BOARD_RESTORE_PLAYER
#define BOARD_RESTORE_PLAYER (board) (board->player = p)
macro to restore player
BOARD_RESTORE_SQUARE
#define BOARD_RESTORE_SQUARE (board, move)
Value:
    switch((move)->n) {  \
    case 18: board->square[(move)->position[18]] = o;  \
    case 17: board->square[(move)->position[17]] = o;  \
    case 16: board->square[(move)->position[16]] = o;  \
    case 15: board->square[(move)->position[15]] = o;  \
    case 14: board->square[(move)->position[14]] = o;  \
    case 13: board->square[(move)->position[13]] = o;  \
    case 12: board->square[(move)->position[12]] = o;  \
    case 11: board->square[(move)->position[11]] = o;  \
    case 10: board->square[(move)->position[10]] = o;  \
    case  9: board->square[(move)->position[ 9]] = o;  \
    case  8: board->square[(move)->position[ 8]] = o;  \
    case  7: board->square[(move)->position[ 7]] = o;  \
    case  6: board->square[(move)->position[ 6]] = o;  \
    case  5: board->square[(move)->position[ 5]] = o;  \
    case  4: board->square[(move)->position[ 4]] = o;  \
    case  3: board->square[(move)->position[ 3]] = o;  \
    case  2: board->square[(move)->position[ 2]] = o;  \
    case  1: board->square[(move)->position[ 1]] = o;  \
    case  0: board->square[(move)->position[ 0]] = EMPTY;  \
}
restore board
BOARD_SIZE
#define BOARD_SIZE 91
size of the board
BOARD_UPDATE_ALL_NODES
#define BOARD_UPDATE_ALL_NODES () board->n_nodes++
more general node counter
BOARD_UPDATE_DISCS
#define BOARD_UPDATE_DISCS (board, n_flips)
Value:
    board->n_discs[(int)p] += n_flips + 1;     \
    board->n_discs[(int)o] -= n_flips;         \
    board->n_empties--;
macro to update disc counter
BOARD_UPDATE_EMPTIES
#define BOARD_UPDATE_EMPTIES (board, empties, x)
Value:
    empties = board->position_to_empties[x];    \
    empties->previous->next = empties->next;    \
    empties->next->previous = empties->previous;
macro to update the list of empty squares
BOARD_UPDATE_HASH_CODE
#define BOARD_UPDATE_HASH_CODE (board, code)
Value:
    board->hash_code[0] ^= code[0];         \
    board->hash_code[1] ^= code[1];
macro to update the hash codes
BOARD_UPDATE_INTERNAL_NODES
#define BOARD_UPDATE_INTERNAL_NODES () board->n_nodes++;
node counter for internal nodes
BOARD_UPDATE_PARITY
#define BOARD_UPDATE_PARITY (board, x) (board->parity[QUADRANT_ID[x]] ^= 1)
macro to update parity
BOARD_UPDATE_PLAYER
#define BOARD_UPDATE_PLAYER (board) (board->player = o)
macro to update player
BOARD_UPDATE_SQUARE
#define BOARD_UPDATE_SQUARE (board, move)
Value:
    switch((move)->n) {  \
    case 18: board->square[(move)->position[18]] = p;  \
    case 17: board->square[(move)->position[17]] = p;  \
    case 16: board->square[(move)->position[16]] = p;  \
    case 15: board->square[(move)->position[15]] = p;  \
    case 14: board->square[(move)->position[14]] = p;  \
    case 13: board->square[(move)->position[13]] = p;  \
    case 12: board->square[(move)->position[12]] = p;  \
    case 11: board->square[(move)->position[11]] = p;  \
    case 10: board->square[(move)->position[10]] = p;  \
    case  9: board->square[(move)->position[ 9]] = p;  \
    case  8: board->square[(move)->position[ 8]] = p;  \
    case  7: board->square[(move)->position[ 7]] = p;  \
    case  6: board->square[(move)->position[ 6]] = p;  \
    case  5: board->square[(move)->position[ 5]] = p;  \
    case  4: board->square[(move)->position[ 4]] = p;  \
    case  3: board->square[(move)->position[ 3]] = p;  \
    case  2: board->square[(move)->position[ 2]] = p;  \
    case  1: board->square[(move)->position[ 1]] = p;  \
    case  0: board->square[(move)->position[ 0]] = p;  \
}
update board
BOARD_UPDATE_TERMINAL_NODES
#define BOARD_UPDATE_TERMINAL_NODES () board->n_nodes++;
node counter for terminal nodes (leaves)
COUNT_NODES
#define COUNT_NODES 3
node counter 0 = off. 1 = internal_nodes, 2 = internal_nodes + leave_nodes, 3 = all. (default = 3, more spectacular!)
EMPTIES_DEEP_TO_SHALLOW_SEARCH
#define EMPTIES_DEEP_TO_SHALLOW_SEARCH 7
depth switch from a slow but efficient PVS near the root to a fast PVS near the leaves. (default = 7)
HASH_TABLE_OK
#define HASH_TABLE_OK (hash_table) (hash_table->hash_mask != 0)
test if hash table exists
INF_SCORE
#define INF_SCORE 127
infinite score: a huge value unreachable as a score and fitting in a char
MAX_FLIP
#define MAX_FLIP 20
maximal number of squares flipped + 1
MAX_MOVE
#define MAX_MOVE 32
maximal number of moves
MAX_SCORE
#define MAX_SCORE 64
maximal score
OPPONENT
#define OPPONENT (p) ((p) ^ 1)
macro to swap colors
PLAY_BEST_MOVE_IN_MEMORY_FIRST
#define PLAY_BEST_MOVE_IN_MEMORY_FIRST (1 && USE_HASH_TABLE)
use the best move stored in the hash table. 1 = on, 0 = off. (default = 1)
PLAY_FAST_SUBTREE_FIRST
#define PLAY_FAST_SUBTREE_FIRST 1
step through the 'smallest' subtree first to find the solution faster. 1 = on, 0 = off. (default = 1)
PLAY_ODD_SQUARE_FIRST
#define PLAY_ODD_SQUARE_FIRST 1
play odd square first 1 = on, 0 = off. (default = 1)
PLAY_STABLEST_SUBTREE
#define PLAY_STABLEST_SUBTREE (1 && PLAY_FAST_SUBTREE_FIRST)
among equally 'small' subtree choose the one with more stable squares. 1 = on, 0 = off. (default = 1)
TICK_TO_DS
#define TICK_TO_DS (t) (int)(((t) / (CLOCKS_PER_SEC / 10)) % 10)
convert clock ticks to tenth of seconds
TICK_TO_H
#define TICK_TO_H (t) (int)((t) / 3600 / CLOCKS_PER_SEC)
convert clock ticks to hours
TICK_TO_M
#define TICK_TO_M (t) (int)(((t) / 60 / CLOCKS_PER_SEC) % 60)
convert clock ticks to minutes
TICK_TO_S
#define TICK_TO_S (t) (int)(((t) / CLOCKS_PER_SEC) % 60)
convert clock ticks to seconds
USE_ENHANCED_TRANSPOSITION_CUTOFF
#define USE_ENHANCED_TRANSPOSITION_CUTOFF (1 && USE_HASH_TABLE)
use the enhanced transposition cutoff heuristic. 1 = on, 0 = off. (default = 1)
USE_HASH_TABLE
#define USE_HASH_TABLE 1
use the hash table heuristics. 1 = on, 0 = off. (default = 1)
USE_PRESORTED_SQUARES
#define USE_PRESORTED_SQUARES 1
use presorted squares. 1 = on, 0 = off. (default = 1)
Typedef Documentation
Board
typedef struct Board Board
board representation
Hash
typedef struct Hash Hash
Hash : item stored in the hash table
HashEntry
typedef struct HashEntry HashEntry
HashEntry: an entry, with two items, of the hash table
HashTable
typedef struct HashTable HashTable
HashTable : hash table
Move
typedef struct Move Move
move representation
MoveList
typedef struct MoveList MoveList
(simple) list of a legal moves
SquareList
typedef struct SquareList SquareList
(double linked) list of squares
Enumeration Type Documentation
anonymous enum
anonymous enum
constants for square coordinates
Enumerator
NOMOVE
PASS
A1
B1
C1
D1
E1
F1
G1
H1
A2
B2
C2
D2
E2
F2
G2
H2
A3
B3
C3
D3
E3
F3
G3
H3
A4
B4
C4
D4
E4
F4
G4
H4
A5
B5
C5
D5
E5
F5
G5
H5
A6
B6
C6
D6
E6
F6
G6
H6
A7
B7
C7
D7
E7
F7
G7
H7
A8
B8
C8
D8
E8
F8
G8
H8
     {
    NOMOVE = 0, PASS,
    A1 = 10, B1, C1, D1, E1, F1, G1, H1,
    A2 = 19, B2, C2, D2, E2, F2, G2, H2,
    A3 = 28, B3, C3, D3, E3, F3, G3, H3,
    A4 = 37, B4, C4, D4, E4, F4, G4, H4,
    A5 = 46, B5, C5, D5, E5, F5, G5, H5,
    A6 = 55, B6, C6, D6, E6, F6, G6, H6,
    A7 = 64, B7, C7, D7, E7, F7, G7, H7,
    A8 = 73, B8, C8, D8, E8, F8, G8, H8
};
anonymous enum
anonymous enum
flipping directions
Enumerator
NW
N
NE
W
E
SW
S
SE
     {
    NW = -10,
    N  =  -9,
    NE =  -8,
     W =  -1,
     E =  +1,
    SW =  +8,
    S  =  +9,
    SE = +10
};
anonymous enum
anonymous enum
constants for colors
Enumerator
BLACK
WHITE
EMPTY
OFF_SIDE
     {
    BLACK = 0,
    WHITE,
    EMPTY,
    OFF_SIDE
};
anonymous enum
anonymous enum
constants for search mode
Enumerator
EXACT_SCORE
WDL_SCORE
WD_SCORE
DL_SCORE
     {
    EXACT_SCORE,
    WDL_SCORE,
    WD_SCORE,
    DL_SCORE
};
Function Documentation
alphabeta_shallow()
int alphabeta_shallow (Board * board, int alpha, int beta, int passed)
Evaluate a position using a shallow Alphabeta.
This function is used when there are few empty squares on the board. Here, optimizations are in favour of speed instead of efficiency. A simple alphabeta is used because of the low branching factor that makes PVS less efficient.
Parameters
board board.
alpha lower bound.
beta upper bound.
passed a flag indicating if previous move was a pass.
Returns
the final score, as a disc difference.
{
    const char p = board->player;
    const char o = OPPONENT(p);
    int score, bestscore = -INF_SCORE;
    SquareList *empties;
    Move move;
#if PLAY_ODD_SQUARE_FIRST
    int parity;
    for (parity = 1; parity >= 0; parity--) {
        for (empties = board->empties->next; empties->position != NOMOVE; empties = empties->next) {
            if (board->parity[QUADRANT_ID[empties->position]] == parity
             && board_do_flip(board, empties->position, &move)) {
#else
        {
        for (empties = board->empties->next; empties->position != NOMOVE; empties = empties->next) {
            if (board_do_flip(board, empties->position, &move)) {
#endif
                BOARD_UPDATE_PLAYER(board);
                BOARD_UPDATE_DISCS(board, move.n);
                BOARD_UPDATE_PARITY(board, *move.position);
                BOARD_UPDATE_EMPTIES(board, empties, *move.position);
                if (board->n_empties == 2) {
                    score = -board_get_final_score_2(board, -beta, -alpha, 0);
                } else {
                    score = -alphabeta_shallow(board, -beta, -alpha, 0);
                }
                BOARD_RESTORE_SQUARE(board, &move);
                BOARD_RESTORE_PLAYER(board);
                BOARD_RESTORE_DISCS(board, move.n);
                BOARD_RESTORE_PARITY(board, *move.position);
                BOARD_RESTORE_EMPTIES(board, empties, *move.position);
                if (score > bestscore) {
                    bestscore = score;
                    if (bestscore > alpha) {
                        alpha = bestscore;
                        if (alpha >= beta) return bestscore;
                    }
                }
            }
        }
    }
    /* no move */
    if (bestscore == -INF_SCORE) {
        if (passed) { /* game over */
            BOARD_CORRECT_TERMINAL_NODES();
            bestscore = board_get_final_score(board);
        } else { /* pass */
            BOARD_UPDATE_PLAYER(board);
            BOARD_UPDATE_INTERNAL_NODES();
            bestscore = -alphabeta_shallow(board, -beta, -alpha, 1);
            BOARD_RESTORE_PLAYER(board);
        }
    }
    return bestscore;
}
References alphabeta_shallow(), BOARD_CORRECT_TERMINAL_NODES, board_do_flip(), board_get_final_score(), board_get_final_score_2(), BOARD_RESTORE_DISCS, BOARD_RESTORE_EMPTIES, BOARD_RESTORE_PARITY, BOARD_RESTORE_PLAYER, BOARD_RESTORE_SQUARE, BOARD_UPDATE_DISCS, BOARD_UPDATE_EMPTIES, BOARD_UPDATE_INTERNAL_NODES, BOARD_UPDATE_PARITY, BOARD_UPDATE_PLAYER, Board::empties, INF_SCORE, Move::n, Board::n_empties, SquareList::next, NOMOVE, OPPONENT, Board::parity, Board::player, Move::position, SquareList::position, and QUADRANT_ID.
Referenced by alphabeta_shallow(), PVS_deep(), and PVS_root().
board_check_move()
int board_check_move (const Board * board, int x, int player)
Check move validity.
Check if a legal move exists on square 'x' for 'player'
Parameters
board board to test
x square on which to move.
player player to move.
Returns
1 if a legal move exists, 0 otherwise.
{
    const char p = player;
    const char o = OPPONENT(p);
    const char *square = board->square + x;
    switch (FLIPPING_DIRECTION_ID[x]) {
    case 1:
        return  (BOARD_CHECK_MOVE_6(SE) ||
                 BOARD_CHECK_MOVE_6(S ) ||
                 BOARD_CHECK_MOVE_6( E));
    case 3:
        return  (BOARD_CHECK_MOVE_6(SW) ||
                 BOARD_CHECK_MOVE_6( W) ||
                 BOARD_CHECK_MOVE_6(S ));
    case 7:
        return  (BOARD_CHECK_MOVE_6(NE) ||
                 BOARD_CHECK_MOVE_6(N ) ||
                 BOARD_CHECK_MOVE_6( E));
    case 9:
        return  (BOARD_CHECK_MOVE_6(NW) ||
                 BOARD_CHECK_MOVE_6(N ) ||
                 BOARD_CHECK_MOVE_6( W));
    case 2:
        return  (BOARD_CHECK_MOVE_6(S ) ||
                 BOARD_CHECK_MOVE_4(SE) ||
                 BOARD_CHECK_MOVE_4(SW) ||
                 BOARD_CHECK_MOVE_4( E) ||
                 BOARD_CHECK_MOVE_4( W));
    case 4:
        return  (BOARD_CHECK_MOVE_6( E) ||
                 BOARD_CHECK_MOVE_4(NE) ||
                 BOARD_CHECK_MOVE_4(SE) ||
                 BOARD_CHECK_MOVE_4(N ) ||
                 BOARD_CHECK_MOVE_4(S ));
    case 6:
        return  (BOARD_CHECK_MOVE_6( W) ||
                 BOARD_CHECK_MOVE_4(NW) ||
                 BOARD_CHECK_MOVE_4(SW) ||
                 BOARD_CHECK_MOVE_4(S ) ||
                 BOARD_CHECK_MOVE_4(N ));
    case 8:
        return  (BOARD_CHECK_MOVE_6(N ) ||
                 BOARD_CHECK_MOVE_4(NE) ||
                 BOARD_CHECK_MOVE_4(NW) ||
                 BOARD_CHECK_MOVE_4( E) ||
                 BOARD_CHECK_MOVE_4( W));
    case 5:
        return  (BOARD_CHECK_MOVE_4(N ) ||
                 BOARD_CHECK_MOVE_4( E) ||
                 BOARD_CHECK_MOVE_4(S ) ||
                 BOARD_CHECK_MOVE_4( W) ||
                 BOARD_CHECK_MOVE_4(NE) ||
                 BOARD_CHECK_MOVE_4(SE) ||
                 BOARD_CHECK_MOVE_4(NW) ||
                 BOARD_CHECK_MOVE_4(SW));
    }
    return 0;
}
References BOARD_CHECK_MOVE_4, BOARD_CHECK_MOVE_6, E, FLIPPING_DIRECTION_ID, N, NE, NW, OPPONENT, S, SE, Board::square, SW, and W.
Referenced by board_get_mobility(), and board_print().
board_count_flips()
int board_count_flips (Board * board, int x, const char p)
Count flipped on the board.
Modify a board by flipping its discs. Only the square[] and player members are modified.
Parameters
board board to modify
x square on which to move.
Returns
the number of disc(s) flipped.
{
    const char o = OPPONENT(p);
    char *square = board->square + x;
    int n_flips = 0;
    switch (FLIPPING_DIRECTION_ID[x]) {
    case 1:
        BOARD_COUNT_FLIPS_6( E);
        BOARD_COUNT_FLIPS_6(S );
        BOARD_COUNT_FLIPS_6(SE);
        break;
    case 3:
        BOARD_COUNT_FLIPS_6( W);
        BOARD_COUNT_FLIPS_6(SW);
        BOARD_COUNT_FLIPS_6(S );
        break;
    case 7:
        BOARD_COUNT_FLIPS_6(N );
        BOARD_COUNT_FLIPS_6(NE);
        BOARD_COUNT_FLIPS_6( E);
        break;
    case 9:
        BOARD_COUNT_FLIPS_6(NW);
        BOARD_COUNT_FLIPS_6(N );
        BOARD_COUNT_FLIPS_6( W);
        break;
    case 2:
        BOARD_COUNT_FLIPS_6(S );
        BOARD_COUNT_FLIPS_4( W);
        BOARD_COUNT_FLIPS_4( E);
        BOARD_COUNT_FLIPS_4(SW);
        BOARD_COUNT_FLIPS_4(SE);
        break;
    case 4:
        BOARD_COUNT_FLIPS_4(N );
        BOARD_COUNT_FLIPS_4(NE);
        BOARD_COUNT_FLIPS_6( E);
        BOARD_COUNT_FLIPS_4(S );
        BOARD_COUNT_FLIPS_4(SE);
        break;
    case 6:
        BOARD_COUNT_FLIPS_4(NW);
        BOARD_COUNT_FLIPS_4(N );
        BOARD_COUNT_FLIPS_6( W);
        BOARD_COUNT_FLIPS_4(SW);
        BOARD_COUNT_FLIPS_4(S );
        break;
    case 8:
        BOARD_COUNT_FLIPS_4(NW);
        BOARD_COUNT_FLIPS_6(N );
        BOARD_COUNT_FLIPS_4(NE);
        BOARD_COUNT_FLIPS_4( W);
        BOARD_COUNT_FLIPS_4( E);
        break;
    case 5:
        BOARD_COUNT_FLIPS_4(NW);
        BOARD_COUNT_FLIPS_4(N );
        BOARD_COUNT_FLIPS_4(NE);
        BOARD_COUNT_FLIPS_4( W);
        BOARD_COUNT_FLIPS_4( E);
        BOARD_COUNT_FLIPS_4(SW);
        BOARD_COUNT_FLIPS_4(S );
        BOARD_COUNT_FLIPS_4(SE);
        break;
    }
    return n_flips;
}
References BOARD_COUNT_FLIPS_4, BOARD_COUNT_FLIPS_6, E, FLIPPING_DIRECTION_ID, N, NE, NW, OPPONENT, S, SE, Board::square, SW, and W.
Referenced by board_get_final_score_1(), and board_get_final_score_2().
board_do_flip()
int board_do_flip (Board * board, int x, Move * move)
Flip discs on the board.
Modify a board by flipping its discs. Only the square[] and player members are modified.
Parameters
board board to modify
x square on which to move.
move a Move structure remembering the modification.
Returns
the number of disc(s) flipped.
{
    const char p = board->player;
    const char o = OPPONENT(p);
    char *square = board->square + x;
    move->n = 0;
    switch (FLIPPING_DIRECTION_ID[x]) {
    case 1:
        BOARD_FLIP(E , 6);
        BOARD_FLIP( S, 6);
        BOARD_FLIP(SE, 6);
        break;
    case 3:
        BOARD_FLIP( W, 6);
        BOARD_FLIP(SW, 6);
        BOARD_FLIP(S , 6);
        break;
    case 7:
        BOARD_FLIP(N , 6);
        BOARD_FLIP(NE, 6);
        BOARD_FLIP( E, 6);
        break;
    case 9:
        BOARD_FLIP(NW, 6);
        BOARD_FLIP(N , 6);
        BOARD_FLIP( W, 6);
        break;
    case 2:
        BOARD_FLIP(S , 6);
        BOARD_FLIP( W, 4);
        BOARD_FLIP( E, 4);
        BOARD_FLIP(SW, 4);
        BOARD_FLIP(SE, 4);
        break;
    case 4:
        BOARD_FLIP(N , 4);
        BOARD_FLIP(NE, 4);
        BOARD_FLIP( E, 6);
        BOARD_FLIP(S , 4);
        BOARD_FLIP(SE, 4);
        break;
    case 6:
        BOARD_FLIP(NW, 4);
        BOARD_FLIP(N , 4);
        BOARD_FLIP( W, 6);
        BOARD_FLIP(SW, 4);
        BOARD_FLIP(S , 4);
        break;
    case 8:
        BOARD_FLIP(NW, 4);
        BOARD_FLIP(N , 6);
        BOARD_FLIP(NE, 4);
        BOARD_FLIP( W, 4);
        BOARD_FLIP( E, 4);
        break;
    case 5:
        BOARD_FLIP(NW, 4);
        BOARD_FLIP(N , 4);
        BOARD_FLIP(NE, 4);
        BOARD_FLIP( W, 4);
        BOARD_FLIP( E, 4);
        BOARD_FLIP(SW, 4);
        BOARD_FLIP(S , 4);
        BOARD_FLIP(SE, 4);
        break;
    }
    if (move->n > 0) {
        *move->position = x;
        *square = p;
        BOARD_UPDATE_PLAYER(board);
        BOARD_UPDATE_INTERNAL_NODES();
    }
    return move->n;
}
References BOARD_FLIP, BOARD_UPDATE_INTERNAL_NODES, BOARD_UPDATE_PLAYER, E, FLIPPING_DIRECTION_ID, N, Move::n, NE, NW, OPPONENT, Board::player, Move::position, S, SE, Board::square, SW, and W.
Referenced by alphabeta_shallow(), and board_get_final_score_2().
board_get_corner_stability()
int board_get_corner_stability (Board * board, int player)
Estimate corner stability.
Count the number of stable discs around the corner. Limiting the count to the corner keep the function fast but still get this information, particularly important at Othello. Corner stability will be used for move sorting.
Parameters
board : the board.
player : the player.
Returns
: the number of stable discs around the corner.
{
    const char *square = board->square;
    const char p = player;
    int n_stables = 0;
    if (square[A1] == p) {
        n_stables++;
    }
    if (square[A8] == p) {
        n_stables++;
    }
    if (square[H1] == p) {
        n_stables++;
    }
    if (square[H8] == p) {
        n_stables++;
    }
    return n_stables;
}
References A1, A8, H1, H8, and Board::square.
Referenced by movelist_sort_fastfirst().
board_get_final_score()
int board_get_final_score (const Board * board)
Get the final score.
Get the final score, when no move can be made.
Parameters
board board.
Returns
the final score, as a disc difference.
{
    const int p = board->player;
    const int o = OPPONENT(p);
    int score = board->n_discs[p] - board->n_discs[o];
    if (score > 0) score += board->n_empties; else if (score < 0) score -= board->n_empties;
    return score;
}
References Board::n_discs, Board::n_empties, OPPONENT, and Board::player.
Referenced by alphabeta_shallow(), PVS_deep(), and solve().
board_get_final_score_0()
int board_get_final_score_0 (const Board * board)
Get the final score.
Get the final score, when the board is full.
Parameters
board board.
Returns
the final score, as a disc difference.
{
    const int p = board->player;
    const int o = OPPONENT(p);
    int score = board->n_discs[p] - board->n_discs[o];
    return score;
}
References Board::n_discs, OPPONENT, and Board::player.
Referenced by PVS_root().
board_get_final_score_1()
int board_get_final_score_1 (Board * board)
Get the final score.
Get the final score, when 1 empty square remains.
Parameters
board board.
Returns
the final score, as a disc difference.
{
    const int p = board->player;
    const int o = OPPONENT(p);
    int score = board->n_discs[p] - board->n_discs[o];
    int n_flips;
    const int x = board->empties->next->position;
    if ((n_flips = board_count_flips(board, x, p)) > 0) {
        score += 2 * n_flips + 1;
        BOARD_UPDATE_TERMINAL_NODES();
    } else if ((n_flips = board_count_flips(board, x, o)) > 0) {
        score -= 2 * n_flips + 1;
        BOARD_UPDATE_TERMINAL_NODES();
    } else if (score < 0) score--;
    else if (score > 0) score++;
    return score;
}
References board_count_flips(), BOARD_UPDATE_TERMINAL_NODES, Board::empties, Board::n_discs, SquareList::next, OPPONENT, Board::player, and SquareList::position.
Referenced by PVS_root().
board_get_final_score_2()
int board_get_final_score_2 (Board * board, int alpha, int beta, int passed)
Get the final score.
Get the final score, when 2 empty squares remain.
Parameters
board the board to evaluate.
alpha upper score value.
beta lower score value.
passed a flag indicating if previous move was a pass.
Returns
the final score, as a disc difference.
{
    const char p = board->player;
    const char o = OPPONENT(p);
    SquareList *empties = board->empties->next;
    int x1 = empties->position;
    int x2 = empties->next->position;
    int score, bestscore, n1_flips, n2_flips, diff_discs;
    Move move;
    diff_discs = board->n_discs[(int)p] - board->n_discs[(int)o];
    bestscore = -INF_SCORE;
    /* try to play on the first available square */
    if ((n1_flips = board_do_flip(board, x1, &move)) > 0) {
        if ((n2_flips = board_count_flips(board, x2, o)) > 0) {
            bestscore = diff_discs + 2 * (n1_flips - n2_flips);
            BOARD_UPDATE_TERMINAL_NODES();
        } else if ((n2_flips = board_count_flips(board, x2, p)) > 0) {
            bestscore = diff_discs + 2 * (n1_flips + n2_flips) + 2;
            BOARD_UPDATE_TERMINAL_NODES();
        } else {
            bestscore = diff_discs + 2 * n1_flips + 1;
            if (bestscore > 0) bestscore++;
            else if (bestscore < 0) bestscore--;
        }
        BOARD_RESTORE_SQUARE(board, &move);
        BOARD_RESTORE_PLAYER(board);
    }
    /* if needed, try to play on the second & last available square */
    if (bestscore < beta && (n1_flips = board_do_flip(board, x2, &move)) > 0) {
        if ((n2_flips = board_count_flips(board, x1, o)) > 0) {
            score = diff_discs + 2 * (n1_flips - n2_flips);
            BOARD_UPDATE_TERMINAL_NODES();
        } else if ((n2_flips = board_count_flips(board, x1, p)) > 0) {
            score = diff_discs + 2 * (n1_flips + n2_flips) + 2;
            BOARD_UPDATE_TERMINAL_NODES();
        } else {
            score = diff_discs + 2 * n1_flips + 1;
            if (score > 0) score++;
            else if (score < 0) score--;
        }
        BOARD_RESTORE_SQUARE(board, &move);
        BOARD_RESTORE_PLAYER(board);
        if (score > bestscore) bestscore = score;
    }
    /* if no move were available */
    if (bestscore == -INF_SCORE) {
        if (passed) { /* game is over */
            BOARD_CORRECT_TERMINAL_NODES();
            bestscore = diff_discs;
            if (bestscore > 0) bestscore += 2;
            else if (bestscore < 0) bestscore -= 2;
        } else { /* pass... */
            BOARD_UPDATE_PLAYER(board);
            BOARD_UPDATE_INTERNAL_NODES();
            bestscore = -board_get_final_score_2(board, -beta, -alpha, 1);
            BOARD_RESTORE_PLAYER(board);
        }
    }
    return bestscore;
}
References BOARD_CORRECT_TERMINAL_NODES, board_count_flips(), board_do_flip(), board_get_final_score_2(), BOARD_RESTORE_PLAYER, BOARD_RESTORE_SQUARE, BOARD_UPDATE_INTERNAL_NODES, BOARD_UPDATE_PLAYER, BOARD_UPDATE_TERMINAL_NODES, Board::empties, INF_SCORE, Board::n_discs, SquareList::next, OPPONENT, Board::player, and SquareList::position.
Referenced by alphabeta_shallow(), board_get_final_score_2(), and PVS_root().
board_get_mobility()
int board_get_mobility (const Board * board, int player)
Estimate the mobility.
Count a number of legal moves for a player. The mobility is an important concept in Othello, used here for move sorting.
Parameters
board : the board to test.
player : the player to test.
Returns
: the number of legal moves.
{
    SquareList *empties;
    int n_moves = 0;
    for (empties = board->empties->next; empties->position != NOMOVE; empties = empties->next) {
        if (board_check_move(board, empties->position, player))
            n_moves++;
    }
    return n_moves;
}
References board_check_move(), Board::empties, SquareList::next, NOMOVE, and SquareList::position.
Referenced by board_print(), and movelist_sort_fastfirst().
board_get_move()
int board_get_move (const Board * board, int x, Move * move)
Compute a move.
Compute how the board will be modified by a move without playing it.
Parameters
board board
x square on which to move.
move a Move structure remembering the modification.
Returns
the number of disc(s) flipped.
{
    const char p = board->player;
    const char o = OPPONENT(p);
    const char *square = board->square + x;
    move->n = 0;
    move->hash_code[0] = hash_code_set_disc[x][(int)p][0];
    move->hash_code[1] = hash_code_set_disc[x][(int)p][1];
    switch (FLIPPING_DIRECTION_ID[x]) {
    case 1:
        BOARD_GET_MOVE( E, 6);
        BOARD_GET_MOVE(S , 6);
        BOARD_GET_MOVE(SE, 6);
        break;
    case 3:
        BOARD_GET_MOVE( W, 6);
        BOARD_GET_MOVE(SW, 6);
        BOARD_GET_MOVE(S , 6);
        break;
    case 7:
        BOARD_GET_MOVE(N , 6);
        BOARD_GET_MOVE(NE, 6);
        BOARD_GET_MOVE( E, 6);
        break;
    case 9:
        BOARD_GET_MOVE(NW, 6);
        BOARD_GET_MOVE(N , 6);
        BOARD_GET_MOVE( W, 6);
        break;
    case 2:
        BOARD_GET_MOVE( W, 4);
        BOARD_GET_MOVE( E, 4);
        BOARD_GET_MOVE(SW, 4);
        BOARD_GET_MOVE(S , 6);
        BOARD_GET_MOVE(SE, 4);
        break;
    case 4:
        BOARD_GET_MOVE(N , 4);
        BOARD_GET_MOVE(NE, 4);
        BOARD_GET_MOVE( E, 6);
        BOARD_GET_MOVE(S , 4);
        BOARD_GET_MOVE(SE, 4);
        break;
    case 6:
        BOARD_GET_MOVE(NW, 4);
        BOARD_GET_MOVE(N , 4);
        BOARD_GET_MOVE( W, 6);
        BOARD_GET_MOVE(SW, 4);
        BOARD_GET_MOVE(S , 4);
        break;
    case 8:
        BOARD_GET_MOVE(NW, 4);
        BOARD_GET_MOVE(N , 6);
        BOARD_GET_MOVE(NE, 4);
        BOARD_GET_MOVE( W, 4);
        BOARD_GET_MOVE( E, 4);
        break;
    case 5:
        BOARD_GET_MOVE(NW, 4);
        BOARD_GET_MOVE(N , 4);
        BOARD_GET_MOVE(NE, 4);
        BOARD_GET_MOVE( W, 4);
        BOARD_GET_MOVE( E, 4);
        BOARD_GET_MOVE(SW, 4);
        BOARD_GET_MOVE(S , 4);
        BOARD_GET_MOVE(SE, 4);
        break;
    }
    if (move->n>0) {
        *move->position = x;
    }
    return move->n;
}
References BOARD_GET_MOVE, E, FLIPPING_DIRECTION_ID, Move::hash_code, N, Move::n, NE, NW, OPPONENT, Board::player, Move::position, S, SE, Board::square, SW, and W.
Referenced by board_get_movelist(), and line_print().
board_get_movelist()
void board_get_movelist (const Board * board, MoveList * start)
Get a list of legal moves.
Compute the complete list of legal moves and store it into a simple linked list, to fasten ulterior move sorting.
Parameters
board : the board to check
start : start point of the linked-list that will received the legal moves.
{
    MoveList *list = start + 1, *previous = start;
    SquareList *empties;
    for (empties = board->empties->next; empties->position != NOMOVE; empties = empties->next) {
        if (board_get_move(board, empties->position, &(list->move))) {
            previous = previous->next = list;
            list++;
        }
    }
    previous->next = NULL;
}
References board_get_move(), Board::empties, MoveList::move, SquareList::next, MoveList::next, NOMOVE, and SquareList::position.
Referenced by PVS_deep(), and solve().
board_print()
void board_print (Board * board, FILE * f)
Initialize the local parity counters.
Approximate the local parity by computing it on each board quadrant. This will be used at the very end of game for move sorting.
Parameters
board : the board.
Print out the board.
Print an ASCII representation of the board to an output stream.
Parameters
board : board to print.
f : output stream.
{
    int i, j, square, x;
    char *color = "*O-.?";
    fputs("  A B C D E F G H\n", f);
    for (i = 1; i <= 8; i++) {
        fputc(i + '0', f);
        fputc(' ', f);
        for (j = 1; j <= 8; j++) {
            x = i * 9 + j;
            square = (int)board->square[x];
            if (square == EMPTY && board_check_move(board, x, board->player))
                square++;
            fputc(color[square], f);
            fputc(' ', f);
        }
        fputc(i+'0', f);
        if (i == 2)
            fprintf(f, " %c to move", color[(int)board->player]);
        else if (i == 4)
            fprintf(f, " *: discs = %2d    moves = %2d",
                board->n_discs[BLACK], board_get_mobility(board, BLACK));
        else if (i == 5)
            fprintf(f, " O: discs = %2d    moves = %2d",
                board->n_discs[WHITE], board_get_mobility(board, WHITE));
        else if (i == 6)
            fprintf(f, "  empties = %2d      ply = %2d",
                board->n_empties, 61-board->n_empties);
        fputc('\n', f);
    }
    fputs("  A B C D E F G H\n", f);
}
References BLACK, board_check_move(), board_get_mobility(), EMPTY, Board::n_discs, Board::n_empties, Board::player, Board::square, and WHITE.
Referenced by main().
board_restore_move()
void board_restore_move (Board * board, const Move * move)
Restore a board.
Restore a board by un-flipping its discs and restoring every other data, according to the 'move' description, in order to cancel a board_update_move.
Parameters
board : board to restore.
move : a Move structure describing the modification.
{
    const char o = board->player;
    const char p = OPPONENT(o);
    SquareList *empties;
    BOARD_RESTORE_SQUARE(board, move);
    BOARD_RESTORE_PLAYER(board);
    BOARD_RESTORE_DISCS(board, move->n);
    BOARD_RESTORE_HASH_CODE(board, move->hash_code);
    BOARD_RESTORE_PARITY(board, *move->position);
    BOARD_RESTORE_EMPTIES(board, empties, *move->position);
}
References BOARD_RESTORE_DISCS, BOARD_RESTORE_EMPTIES, BOARD_RESTORE_HASH_CODE, BOARD_RESTORE_PARITY, BOARD_RESTORE_PLAYER, BOARD_RESTORE_SQUARE, Move::hash_code, Move::n, OPPONENT, Board::player, and Move::position.
Referenced by PVS_deep(), and PVS_root().
board_restore_pass()
void board_restore_pass (Board * board)
Un-passing.
Restore a board by un-passing player's turn.
Parameters
board : board to restore.
{
    const char p = OPPONENT(board->player);
    BOARD_RESTORE_PLAYER(board);
    BOARD_RESTORE_HASH_CODE(board, hash_code_swap_player);
}
References BOARD_RESTORE_HASH_CODE, BOARD_RESTORE_PLAYER, OPPONENT, and Board::player.
Referenced by PVS_deep(), and solve().
board_set()
void board_set (Board * board, const char * string)
Set a board from a string description.
Read a standardized string (See http://www.nada.kth.se/~gunnar/download2.html for details) and translate it into our internal Board structure.
Parameters
board : the board to set
string : string describing the board
{
    int i, j;
    SquareList *empties;
#if USE_PRESORTED_SQUARES
    const int presorted_position[] = {
        A1, A8, H1, H8,                    /* Corner */
        A3, A6, C1, C8, F1, F8, H3, H6,    /* A */
        C3, C6, F3, F6,                    /* D */
        A4, A5, D1, D8, E1, E8, H4, H5,    /* B */
        C4, C5, D3, D6, E3, E6, F4, F5,    /* E */
        B4, B5, D2, D7, E2, E7, G4, G5,    /* G */
        B3, B6, C2, C7, F2, F7, G3, G6,    /* F */
        A2, A7, B1, B8, G1, G8, H2, H7,    /* C */
        B2, B7, G2, G7,                    /* X */
    };
#else
    const int presorted_position[] = {     /* A1 -> H8 */
        A1, A2, A3, A4, A5, A6, A7, A8,
        B1, B2, B3, B4, B5, B6, B7, B8,
        C1, C2, C3, C4, C5, C6, C7, C8,
        D1, D2, D3,         D6, D7, D8,
        E1, E2, E3,         E6, E7, E8,
        F1, F2, F3, F4, F5, F6, F7, F8,
        G1, G2, G3, G4, G5, G6, G7, G8,
        H1, H2, H3, H4, H5, H6, H7, H8
    };
#endif
    for (i=0; i < BOARD_SIZE; i++) board->square[i] = OFF_SIDE;
    board->n_discs[BLACK] = board->n_discs[WHITE] = board->n_empties = 0;
    for (i = A1; i <= H8; i += 9)
    for (j = i; j < i + 8; j++) {
        if (*string == '\0') break;
        switch (tolower(*string)) {
        case 'b':
        case 'x':
        case '*':
            board->square[j] = BLACK;
            board->n_discs[BLACK]++;
            break;
        case 'o':
        case 'w':
            board->square[j] = WHITE;
            board->n_discs[WHITE]++;
            break;
        case '-':
        case '.':
            board->square[j] = EMPTY;
            board->n_empties++;
            break;
        default:
            j--;
            break;
        }
        string++;
    }
    board->player = EMPTY;
    for (;*string != '\0' && board->player == EMPTY; string++) {
        switch (tolower(*string)) {
        case 'b':
        case 'x':
        case '*':
            board->player = BLACK;
            break;
        case 'o':
        case 'w':
            board->player = WHITE;
            break;
        default:
            break;
        }
    }
    if (board->player == EMPTY) {
        fprintf(stderr, "board_set: incorrect player value '%c'\n", *string);
        exit(EXIT_FAILURE);
    }
    /* init Empties */
    empties = board->empties;
    empties->position = NOMOVE; /* sentinel */
    empties->previous = NULL;
    empties->next = empties + 1;
    empties = empties->next;
    for (i = 0; i < 60; i++) {    /* add empty squares */
        if (board->square[presorted_position[i]] == EMPTY) {
            empties->position = presorted_position[i];
            empties->previous = empties - 1;
            empties->next = empties + 1;
            board->position_to_empties[presorted_position[i]] = empties;
            empties = empties->next;
        }
    }
    empties->position = NOMOVE; /* sentinel */
    empties->previous = empties - 1;
    empties->next = NULL;
    /* set hash_code */
    board->hash_code[0] = board->hash_code[1] = 0;
    if ((board->player == WHITE) ^ ((board->n_empties & 1) == 1)) {
        board->hash_code[0] ^= hash_code_swap_player[0];
        board->hash_code[1] ^= hash_code_swap_player[1];
    }
    for (i = A1; i <= H8; i += 9)
    for (j = i; j < i + 8; j++) {
        board->hash_code[0] ^= hash_code_set_disc[j][(int)board->square[j]][0];
        board->hash_code[1] ^= hash_code_set_disc[j][(int)board->square[j]][1];
    }
    /* init parity */
    board->parity[0] = board->parity[1] = board->parity[2] = board->parity[3] = 0;
    for (empties = board->empties->next; empties->position != NOMOVE; empties = empties->next) {
        board->parity[QUADRANT_ID[empties->position]] ^= 1;
    }
    /* nodes */
    board->n_nodes = 0;
}
References A1, A2, A3, A4, A5, A6, A7, A8, B1, B2, B3, B4, B5, B6, B7, B8, BLACK, BOARD_SIZE, C1, C2, C3, C4, C5, C6, C7, C8, D1, D2, D3, D6, D7, D8, E1, E2, E3, E6, E7, E8, Board::empties, EMPTY, F1, F2, F3, F4, F5, F6, F7, F8, G1, G2, G3, G4, G5, G6, G7, G8, H1, H2, H3, H4, H5, H6, H7, H8, Board::hash_code, Board::n_discs, Board::n_empties, Board::n_nodes, SquareList::next, NOMOVE, OFF_SIDE, Board::parity, Board::player, SquareList::position, Board::position_to_empties, SquareList::previous, QUADRANT_ID, Board::square, and WHITE.
Referenced by main().
board_update_move()
void board_update_move (Board * board, const Move * move)
Update a board.
Update a board by flipping its discs and updating every other data, according to the 'move' description.
Parameters
board : the board to modify
move : A Move structure describing the modification.
{
    const char p = board->player;
    const char o = OPPONENT(p);
    SquareList *empties;
    BOARD_UPDATE_SQUARE(board, move);
    BOARD_UPDATE_PLAYER(board);
    BOARD_UPDATE_DISCS(board, move->n);
    BOARD_UPDATE_INTERNAL_NODES();
    BOARD_UPDATE_HASH_CODE(board, move->hash_code);
    BOARD_UPDATE_PARITY(board, *move->position);
    BOARD_UPDATE_EMPTIES(board, empties, *move->position);
}
References BOARD_UPDATE_DISCS, BOARD_UPDATE_EMPTIES, BOARD_UPDATE_HASH_CODE, BOARD_UPDATE_INTERNAL_NODES, BOARD_UPDATE_PARITY, BOARD_UPDATE_PLAYER, BOARD_UPDATE_SQUARE, Move::hash_code, Move::n, OPPONENT, Board::player, and Move::position.
Referenced by PVS_deep(), and PVS_root().
board_update_pass()
void board_update_pass (Board * board)
Passing move.
Modify a board by passing player's turn.
Parameters
board : board to update.
{
    const char o = OPPONENT(board->player);
    BOARD_UPDATE_PLAYER(board);
    BOARD_UPDATE_INTERNAL_NODES();
    BOARD_UPDATE_HASH_CODE(board, hash_code_swap_player);
}
References BOARD_UPDATE_HASH_CODE, BOARD_UPDATE_INTERNAL_NODES, BOARD_UPDATE_PLAYER, OPPONENT, and Board::player.
Referenced by PVS_deep(), and solve().
hash_clear()
void hash_clear (HashTable * hash_table)
Clear the hashtable.
Set all hash table entries to zero.
Parameters
hash_table hash table to clear.
{
    unsigned long i;
    static const HashEntry init_entry = {
        {0, -INF_SCORE, +INF_SCORE, 0, 0},
        {0, -INF_SCORE, +INF_SCORE, 0, 0}};
    if (HASH_TABLE_OK(hash_table)) {
        for (i = 0; i <= hash_table->hash_mask; i++) {
            hash_table->hash_entry[i] = init_entry;
        }
    }
}
References HashTable::hash_entry, HashTable::hash_mask, HASH_TABLE_OK, and INF_SCORE.
Referenced by main().
hash_free()
void hash_free (HashTable * hash_table)
Free the hashtable.
Free the memory allocated by the hash table entries
Parameters
hash_table hash_table to free.
{
    free(hash_table->hash_entry);
    hash_table->hash_entry = NULL;
}
References HashTable::hash_entry.
Referenced by main().
hash_get()
Hash * hash_get (HashTable * hash_table, const Board * board)
Find an hash table entry according to the evaluated board hash codes.
The data recorded within the entry will then be used to reframe the alpha beta bounds and set the move to search first. In some cases, an alphabeta cut will be immediately found so avoiding the entire search and gaining a (lot of) time.
Parameters
hash_table : hash table.
board : evaluated board.
Returns
: an hash table entry if the board was found, NULL otherwise.
{
    HashEntry *hash_entry;
    if (HASH_TABLE_OK(hash_table)) {
        hash_entry = hash_table->hash_entry + board->hash_code[0];
        if (board->hash_code[1] == hash_entry->deepest.lock)
            return &(hash_entry->deepest);
        if (board->hash_code[1] == hash_entry->newest.lock)
            return &(hash_entry->newest);
    }
    return NULL;
}
References HashEntry::deepest, Board::hash_code, HashTable::hash_entry, HASH_TABLE_OK, Hash::lock, and HashEntry::newest.
Referenced by line_print(), and PVS_deep().
hash_init()
void hash_init (HashTable * hash_table, int n_bits)
Initialise the hashtable.
Allocate the hash table entries and initialise the hash masks and codes.
Parameters
hash_table hash table to setup.
n_bits requested size for the hash table in number of bits.
{
    int i,j;
    unsigned long hash_mask[2], size = 1u << n_bits;
    if (hash_table->hash_entry != NULL) free(hash_table->hash_entry);
    hash_table->hash_entry = malloc(size * sizeof (HashEntry));
    if (hash_table->hash_entry == NULL) {
        fprintf(stderr, "hash_init: cannot allocate the hash table\n");
        exit(EXIT_FAILURE);
    }
    hash_mask[0] = hash_table->hash_mask = size - 1;
    hash_mask[1] = 0xffffffff;
    for (j = 0; j < 2; j++) {
        hash_code_swap_player[j] = (hash_random() & hash_mask[j]);
        for (i = 0; i < BOARD_SIZE; i++) {
            hash_code_set_disc[i][BLACK][j] = (hash_random() & hash_mask[j]);
            hash_code_set_disc[i][WHITE][j] = (hash_random() & hash_mask[j]);
            hash_code_set_disc[i][EMPTY][j] = 0;
            hash_code_flip_disc[i][j] = hash_code_set_disc[i][BLACK][j] ^
                hash_code_set_disc[i][WHITE][j];
            hash_code_set_disc[i][BLACK][j] ^= hash_code_swap_player[j];
            hash_code_set_disc[i][WHITE][j] ^= hash_code_swap_player[j];
        }
    }
}
References BLACK, BOARD_SIZE, EMPTY, HashTable::hash_entry, HashTable::hash_mask, hash_random(), and WHITE.
Referenced by main().
hash_random()
unsigned long hash_random (void)
Pseudo-random number generator.
A good random generator (similar to rand48 or Java's one) to set the hash codes.
Returns
a 32 bits random unsigned long integer.
{
    static unsigned long x[3] = {0xe66du, 0xdeecu, 0x5u};
    const unsigned long MASK = 0x0000ffffu;
    const unsigned long A[3] = {0xe66du, 0xdeecu, 0x5u};
    const unsigned long B = 0xBu;
    unsigned long product[3];
    product[0] = A[0] * x[0] + B;
    product[1] = A[1] * x[0] + (product[0] >> 16);
    product[2] = A[1] * x[1] + A[0] * x[2] + A[2] * x[0] + (product[1] >> 16);
    product[1] = A[0] * x[1] + (product[1] & MASK);
    product[2] += (product[1] >> 16);
    x[0] = (product[0] & MASK);
    x[1] = (product[1] & MASK);
    x[2] = (product[2] & MASK);
    return x[1] + (x[2] << 16);
}
Referenced by hash_init().
hash_update()
void hash_update (HashTable * hash_table, const Board * board, int alpha, int beta, int score, int move)
Update an hashtable entry.
Find an hash table entry according to the evaluated board hash codes. Then update the entry if it already exists otherwise create a new one. Collisions are managed in such a way that better existing entries are always preserved and the new evaluated data is always added. Lower and upper score bounds are then updated/set from the alpha, beta and score values according to the following alphabeta property (where alpha < beta): -if (score >= beta) score is a lower bound of the real score -if (score <= alpha) score is an upper bound of the real score -if (alpha < score && score < beta) score equals the real score So:
-if (score < beta) update the upper bound of the hash entry -if (score > alpha) update the lower bound of the hash entry The best move is also stored.
Parameters
hash_table hash table to update.
board evaluated board.
alpha alpha bound when calling the alphabeta function.
beta beta bound when calling the alphabeta function.
score best score found.
move best move found.
{
    HashEntry *hash_entry;
    Hash *deepest, *newest;
    if (!HASH_TABLE_OK(hash_table)) return;
    hash_entry = hash_table->hash_entry + board->hash_code[0];
    deepest = &(hash_entry->deepest);
    newest = &(hash_entry->newest);
    /* try to update deepest entry */
    if (board->hash_code[1] == deepest->lock) {
        if (score < beta && score < deepest->upper)
            deepest->upper = (char) score;
        if (score > alpha && score > deepest->lower)
            deepest->lower = (char) score;
        deepest->move = (char) move;
    /* else try to update newest entry */
    } else if (board->hash_code[1] == newest->lock) {
        if (score < beta && score < newest->upper)
            newest->upper = (char) score;
        if (score > alpha && score > newest->lower)
            newest->lower = (char) score;
        newest->move = (char) move;
    /* else try to add to deepest entry */
    } else if (deepest->depth < board->n_empties) {
        if (newest->depth < deepest->depth) *newest = *deepest;
        deepest->lock = board->hash_code[1];
        deepest->depth = (char) board->n_empties;
        deepest->lower = -INF_SCORE;
        deepest->upper = +INF_SCORE;
        if (score < beta) deepest->upper = (char) score;
        if (score > alpha) deepest->lower = (char) score;
        deepest->move = (char) move;
    /* else add to newest entry */
    } else {
        newest->lock = board->hash_code[1];
        newest->depth = (char) board->n_empties;
        newest->lower = -INF_SCORE;
        newest->upper = +INF_SCORE;
        if (score < beta) newest->upper = (char) score;
        if (score > alpha) newest->lower = (char) score;
        newest->move = (char) move;
    }
}
References HashEntry::deepest, Hash::depth, Board::hash_code, HashTable::hash_entry, HASH_TABLE_OK, INF_SCORE, Hash::lock, Hash::lower, Hash::move, Board::n_empties, HashEntry::newest, and Hash::upper.
Referenced by PVS_deep(), and PVS_root().
line_print()
void line_print (Board * board, HashTable * hash_table, int depth, FILE * f)
Print a PV.
Get the Principal Variation (best move sequence) from the hash table, and print it to the output stream.
Parameters
board starting position.
hash_table hash table where to retrieve the moves.
depth maximum number of moves to print.
f output stream.
{
    const char p = board->player;
    const char o = OPPONENT(p);
    Hash *hash = hash_get(hash_table, board);
    Move move[1];
    if (depth <= 0) return;
    if (hash != NULL) {
        move_print(hash->move, board->player, f);
        fputc(' ',f);
        if (board_get_move(board, hash->move, move)) {
            BOARD_UPDATE_SQUARE(board, move);
            BOARD_UPDATE_PLAYER(board);
            BOARD_UPDATE_HASH_CODE(board, move->hash_code);
            line_print(board, hash_table, depth - 1, f);
            BOARD_RESTORE_SQUARE(board, move);
            BOARD_RESTORE_PLAYER(board);
            BOARD_RESTORE_HASH_CODE(board, move->hash_code);
        } else if (hash->move == PASS) {
            BOARD_UPDATE_PLAYER(board);
            BOARD_UPDATE_HASH_CODE(board, hash_code_swap_player);
            line_print(board, hash_table, depth - 1, f);
            BOARD_RESTORE_PLAYER(board);
            BOARD_RESTORE_HASH_CODE(board, hash_code_swap_player);
        } else {
            line_print(board, hash_table, depth - 1, f);
        }
    } else {
        fputs("-- ", f);
        line_print(board, hash_table, depth - 1, f);
    }
}
References board_get_move(), BOARD_RESTORE_HASH_CODE, BOARD_RESTORE_PLAYER, BOARD_RESTORE_SQUARE, BOARD_UPDATE_HASH_CODE, BOARD_UPDATE_PLAYER, BOARD_UPDATE_SQUARE, Move::hash_code, hash_get(), line_print(), Hash::move, move_print(), OPPONENT, PASS, and Board::player.
Referenced by line_print(), and main().
main()
int main (int argc, char ** argv)
Program main function.
Read optional parameters and a script file name from the command line. Then loop through the positions provided in the script file, solving each one according to the chosen options.
Parameters
argc number of arguments.
argv arguments.
Returns
SUCCESS_EXIT or SUCCESS_FAILURE.
{
    Board board;
    Move bestmove;
    char *file_name = NULL, problem[256];
    FILE *file;
    clock_t t, T = 0;
    int i, verbose = 0, mode = EXACT_SCORE;
    double nodes = 0.0;
    HashTable hash_table = {NULL, 0};
#if COUNT_NODES > 0
    const char *HEADER = "\n # |depth|score|   principal variation   |   time    | nodes (N)  | speed (N/s)";
    const char *SEPARATOR = "-------------------------------------------------------------------------------";
#else
    const char *HEADER = "\n # |depth|score|   principal variation   |   time";
    const char *SEPARATOR = "-----------------------------------------------------";
#endif
    /* parse arguments */
    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-vv") == 0) verbose = 2;
        else if (strcmp(argv[i], "-v") == 0) verbose = 1;
        else if (strcmp(argv[i], "-h") == 0 && i + 1 < argc)
            hash_init(&hash_table, atoi(argv[++i]));
        else if (file_name == NULL) file_name = argv[i];
        else usage();
    }
    /* open script file */
    if (file_name == NULL) usage();
    file = fopen(file_name, "r");
    if (file == NULL) {
        fprintf(stderr, "solver: cannot open script file %s\n", file_name);
        exit(EXIT_FAILURE);
    }
    /* loop through problems */
    if (verbose == 1) {
        puts(HEADER);
        puts(SEPARATOR);
    }
    for (i = 0; fgets(problem, 256, file) ; i++) {
        if (*problem == '%') continue;
        board_set(&board, problem);
        if (verbose == 2) {
            board_print(&board, stdout);
            puts(HEADER);
            puts(SEPARATOR);
        }
        t = clock();
#if USE_HASH_TABLE
        hash_clear(&hash_table);
#endif
        solve(&board, &hash_table, board.n_empties, &bestmove);
        t = clock() - t;
        T += t;
        nodes += board.n_nodes;
        if (verbose) {
            printf("%3d|", i + 1);
            printf("  %2d |", board.n_empties);
            printf(" %+03d | ", bestmove.score);
            if (hash_table.hash_mask != 0) {
                line_print(&board, &hash_table, 8, stdout);
            } else {
                move_print(*bestmove.position, board.player, stdout);
                printf(" -- -- -- -- -- -- -- ");
            }
            printf("| %d:%02d:%02d.%1d ", TICK_TO_H(t), TICK_TO_M(t), TICK_TO_S(t), TICK_TO_DS(t));
#if COUNT_NODES > 0
            printf("|%11.0f |", board.n_nodes);
            if (t > 0) printf(" %9.0f", board.n_nodes / t * CLOCKS_PER_SEC);
#endif
            putchar('\n');
            if (verbose == 2) putchar('\n');
            fflush(stdout);
        }
#ifdef _WIN32
        if (priority == THREAD_PRIORITY_TIME_CRITICAL) {
            Sleep(100);
        }
#endif
    }
    if (verbose) puts(SEPARATOR);
#if COUNT_NODES > 0
    printf("%.30s : %.0f nodes in ",file_name, nodes);
    printf("%d:%02d:%02d.%1d",
        TICK_TO_H(T), TICK_TO_M(T), TICK_TO_S(T), TICK_TO_DS(T));
    if (T > 0) printf(" %.0f nodes/s.", nodes * CLOCKS_PER_SEC / T);
    printf("\n\n");
#else
    printf("%.30s : %d:%02d:%02d.%1d\n\n",
        file_name, TICK_TO_H(T), TICK_TO_M(T), TICK_TO_S(T), TICK_TO_DS(T));
#endif
    /* close files & free allocated data */
    fclose(file);
    hash_free(&hash_table);
    return EXIT_SUCCESS;
}
References board_print(), board_set(), EXACT_SCORE, hash_clear(), hash_free(), hash_init(), HashTable::hash_mask, line_print(), move_print(), Board::n_empties, Board::n_nodes, Board::player, Move::position, Move::score, solve(), TICK_TO_DS, TICK_TO_H, TICK_TO_M, TICK_TO_S, and usage().
move_print()
void move_print (int x, int player, FILE * f)
Print out a move.
Print the move, using letter case to distinguish player's color, to an output stream.
Parameters
x square coordinate to print.
player player color.
f output stream.
{
    int s[2];
    if (x == NOMOVE) {
        s[0] = ' ';
        s[1] = ' ';
    } else if (x == PASS) {
        s[0] = 'p';
        s[1] = 's';
    } else if (x >= A1 && x <= H8 && x % 9 > 0) {
        s[0] = x % 9 + 'a' - 1;
        s[1] = x / 9 + '1' - 1;
    } else {
        s[0] = '?';
        s[1] = '?';
    }
    if (player == BLACK) {
        s[0] = toupper(s[0]);
        s[1] = toupper(s[1]);
    }
    fputc(s[0], f);
    fputc(s[1], f);
}
References A1, BLACK, NOMOVE, and PASS.
Referenced by line_print(), and main().
movelist_sort_bestmove()
void movelist_sort_bestmove (MoveList * movelist, int move)
Sort a move as best.
Put a move at the head of the list.
Parameters
movelist list of moves to sort.
move best move to to set first.
{
    MoveList *iter, *previous;
    for (iter = (previous = movelist)->next; iter != NULL; iter = (previous = iter)->next) {
        if (*iter->move.position == move) {
            previous->next = iter->next;
            iter->next = movelist->next;
            movelist->next = iter;
            break;
        }
    }
}
References MoveList::move, MoveList::next, and Move::position.
Referenced by PVS_deep(), and PVS_root().
movelist_sort_fastfirst()
void movelist_sort_fastfirst (MoveList * movelist, Board * board)
Sort a list of move, fastest-first.
Sort a list to accelerate the alphabeta research. The moves that minimize opponent mobility and increase player's relative stability will be played first.
Parameters
movelist : list of moves to sort.
board : board on which the moves applied.
{
    MoveList *iter, *best, *previous_best, *previous;
    SquareList *empties;
    const char p = board->player;
    const char o = OPPONENT(p);
    for (iter = movelist->next; iter != NULL; iter = iter->next) {
        BOARD_UPDATE_SQUARE(board, &(iter->move));
        BOARD_LAST_UPDATE_EMPTIES(board, empties, *iter->move.position);
        BOARD_UPDATE_ALL_NODES();
#if PLAY_STABLEST_SUBTREE
        iter->move.score = (board_get_mobility(board, o) << 4) - board_get_corner_stability(board, p);
#else
        iter->move.score = board_get_mobility(board, o);
#endif
        BOARD_RESTORE_SQUARE(board, &(iter->move));
        BOARD_LAST_RESTORE_EMPTIES(board, empties, *iter->move.position);
    }
    for (iter = movelist; iter->next != NULL; iter = iter->next) {
        previous_best = iter;
        for (previous = previous_best->next; previous->next != NULL;
            previous = previous->next) {
            if (previous_best->next->move.score >  previous->next->move.score) {
                previous_best = previous;
            }
        }
        if (previous_best != iter) {
            best = previous_best->next;
            previous_best->next = best->next;
            best->next = iter->next;
            iter->next = best;
        }
    }
}
References board_get_corner_stability(), board_get_mobility(), BOARD_LAST_RESTORE_EMPTIES, BOARD_LAST_UPDATE_EMPTIES, BOARD_RESTORE_SQUARE, BOARD_UPDATE_ALL_NODES, BOARD_UPDATE_SQUARE, MoveList::move, MoveList::next, OPPONENT, Board::player, Move::position, and Move::score.
Referenced by PVS_deep(), and solve().
PVS_deep()
int PVS_deep (Board * board, HashTable * hash_table, int alpha, int beta, int passed)
Evaluate a position with a deep Principal Variation Search algorithm.
This function is used when there are still many empty squares on the board. Move ordering, hash table cutoff, enhanced transposition cutoff, etc. are used in order to diminish the size of the tree to analyse, but at the expense of a slower speed.
Parameters
board board.
hash_table hash_table.
alpha lower bound.
beta upper bound.
passed a flag indicating if previous move was a pass.
Returns
the final score, as a disc difference.
{
    int score, bestscore, lower, upper, bestmove;
    unsigned long hash_lock, hash_index;
    MoveList movelist[MAX_MOVE + 2], *iter;
    Move *move;
    Hash *hash;
    HashEntry *hash_entry;
    bestmove = NOMOVE;
    lower = alpha;
    upper = beta;
    /* transposition cutoff ? */
#if USE_HASH_TABLE
    hash = hash_get(hash_table, board);
    if (hash != NULL) {
        if (upper > hash->upper) {
            upper = hash->upper;
            if (upper <= lower) return upper;
        }
        if (lower < hash->lower) {
            lower = hash->lower;
            if (lower >= upper) return lower;
        }
        bestmove = hash->move;
    }
#endif
    board_get_movelist(board, movelist);
    if (movelist->next == NULL) {
        if (passed) {
            BOARD_CORRECT_TERMINAL_NODES();
            alpha = -(beta = +INF_SCORE);
            bestscore = board_get_final_score(board);
            bestmove = NOMOVE;
        } else {
            board_update_pass(board);
            bestscore = -PVS_deep(board, hash_table, -upper, -lower, 1);
            bestmove = PASS;
            board_restore_pass(board);
        }
    } else {
        /* enhanced transposition cutoff */
#if USE_ENHANCED_TRANSPOSITION_CUTOFF
        if (board->n_empties > EMPTIES_DEEP_TO_SHALLOW_SEARCH &&
            HASH_TABLE_OK(hash_table)) {
            if (bestmove != NOMOVE) movelist_sort_bestmove(movelist, bestmove);
            for (iter = movelist->next; iter != NULL; iter = iter->next) {
                move = &(iter->move);
                hash_index = (board->hash_code[0] ^ move->hash_code[0]);
                hash_lock = (board->hash_code[1] ^ move->hash_code[1]);
                hash_entry = hash_table->hash_entry + hash_index;
                BOARD_UPDATE_ALL_NODES();
                if (hash_entry->deepest.lock ==  hash_lock && -hash_entry->deepest.upper >= upper)
                    return -hash_entry->deepest.upper;
                if (hash_entry->newest.lock ==  hash_lock && -hash_entry->newest.upper >= upper)
                    return -hash_entry->newest.upper;
            }
        }
#endif
        /* move sorting */
#if PLAY_FAST_SUBTREE_FIRST
        if (board->n_empties > EMPTIES_DEEP_TO_SHALLOW_SEARCH)
            movelist_sort_fastfirst(movelist, board);
#endif
#if PLAY_BEST_MOVE_IN_MEMORY_FIRST
        if (bestmove != NOMOVE && bestmove != *movelist->next->move.position)
            movelist_sort_bestmove(movelist, bestmove);
#endif
        /* first move */
        iter = movelist->next;
        move = &(iter->move);
        board_update_move(board, move);
        if (board->n_empties < EMPTIES_DEEP_TO_SHALLOW_SEARCH) {
            bestscore = -alphabeta_shallow(board, -upper, -lower, 0);
        } else {
            bestscore = -PVS_deep(board, hash_table, -upper, -lower, 0);
        }
        bestmove = *move->position;
        if (bestscore > lower) lower = bestscore;
        board_restore_move(board, move);
        /* other moves : try to refute the first/best one */
        for (iter = iter->next; lower < upper && iter != NULL; iter = iter->next) {
            move = &(iter->move);
            board_update_move(board, move);
            if (board->n_empties < EMPTIES_DEEP_TO_SHALLOW_SEARCH) {
                score = -alphabeta_shallow(board, -lower - 1, -lower, 0);
                if (lower < score && score < upper)
                    score = -alphabeta_shallow(board, -upper, -score, 0);
            } else {
                score = -PVS_deep(board, hash_table, -lower - 1, -lower, 0);
                if (lower < score && score < upper)
                    score = -PVS_deep(board, hash_table, -upper, -score, 0);
            }
            board_restore_move(board, move);
            if (score > bestscore) {
                bestscore = score;
                bestmove = *move->position;
                if (bestscore > lower) lower = bestscore;
            }
        }
    }
#if USE_HASH_TABLE
    hash_update(hash_table, board, alpha, beta, bestscore, bestmove);
#endif
    return bestscore;
}
References alphabeta_shallow(), BOARD_CORRECT_TERMINAL_NODES, board_get_final_score(), board_get_movelist(), board_restore_move(), board_restore_pass(), BOARD_UPDATE_ALL_NODES, board_update_move(), board_update_pass(), HashEntry::deepest, EMPTIES_DEEP_TO_SHALLOW_SEARCH, Move::hash_code, Board::hash_code, HashTable::hash_entry, hash_get(), HASH_TABLE_OK, hash_update(), INF_SCORE, Hash::lock, Hash::lower, MAX_MOVE, MoveList::move, Hash::move, movelist_sort_bestmove(), movelist_sort_fastfirst(), Board::n_empties, HashEntry::newest, MoveList::next, NOMOVE, PASS, Move::position, PVS_deep(), and Hash::upper.
Referenced by PVS_deep(), and PVS_root().
PVS_root()
void PVS_root (Board * board, HashTable * hash_table, int alpha, int beta, int depth, MoveList * movelist)
Principal Variation Search algorithm at the root of the tree.
This function solves the position provided within the limits set by the alpha and beta bounds. The movelist parameter is updated so that the bestmove is the first of the list when the search ended.
Parameters
board board.
hash_table hash table to memorize the analysis.
alpha lower bound.
beta upper bound.
movelist List of legal moves (should actually contain moves !).
{
    int lower, upper;
    MoveList *iter;
    Move *move, *bestmove;
    lower = alpha;
    upper = beta;
    board->n_nodes++;
    /* first move */
    iter = movelist->next;
    bestmove = &(iter->move);
    board_update_move(board, bestmove);
    if (board->n_empties == 0) {
        bestmove->score = -board_get_final_score_0(board);
    } else if (board->n_empties == 1) {
        bestmove->score = -board_get_final_score_1(board);
    } else if (board->n_empties == 2) {
        bestmove->score = -board_get_final_score_2(board, -upper, -lower, 0);
    } else if (board->n_empties < EMPTIES_DEEP_TO_SHALLOW_SEARCH) {
        bestmove->score = -alphabeta_shallow(board, -upper, -lower, 0);
    } else {
        bestmove->score = -PVS_deep(board, hash_table, -upper, -lower, 0);
    }
    if (bestmove->score > lower) lower = bestmove->score;
    board_restore_move(board, bestmove);
    /* other moves : try to refute the first/best one */
    for (iter = iter->next; lower < upper && iter != NULL; iter = iter->next) {
        move = &(iter->move);
        board_update_move(board, move);
        if (board->n_empties == 0) {
            move->score = -board_get_final_score_0(board);
        } else if (board->n_empties == 1) {
            move->score = -board_get_final_score_1(board);
        } else if (board->n_empties == 2) {
            move->score = -board_get_final_score_2(board, -upper, -lower, 0);
        } else if (board->n_empties < EMPTIES_DEEP_TO_SHALLOW_SEARCH) {
            move->score = -alphabeta_shallow(board, -lower - 1, -lower, 0);
            if (lower < move->score && move->score < upper)
                move->score = -PVS_deep(board, hash_table, -upper, -move->score, 0);
        } else {
            move->score = -PVS_deep(board, hash_table, -lower - 1, -lower, 0);
            if (lower < move->score && move->score < upper)
                move->score = -PVS_deep(board, hash_table, -upper, -move->score, 0);
        }
        board_restore_move(board, move);
        if (move->score > bestmove->score) {
            bestmove = move;
            if (bestmove->score > lower) lower = bestmove->score;
        }
    }
    movelist_sort_bestmove(movelist, *bestmove->position);
#if USE_HASH_TABLE
    hash_update(hash_table, board, alpha, beta, bestmove->score, *bestmove->position);
#endif
}
References alphabeta_shallow(), board_get_final_score_0(), board_get_final_score_1(), board_get_final_score_2(), board_restore_move(), board_update_move(), EMPTIES_DEEP_TO_SHALLOW_SEARCH, hash_update(), MoveList::move, movelist_sort_bestmove(), Board::n_empties, Board::n_nodes, MoveList::next, Move::position, PVS_deep(), and Move::score.
Referenced by solve().
solve()
void solve (Board * board, HashTable * hash_table, int depth, Move * bestmove)
Search the bestmove of a given board.
Depending on the mode, the function will try to solve for a draw (DL_SCORE), a win (WD_SCORE), the exact outcome (WDL_SCORE) or the exact score. For the latter case, aspiration windows have been implemented. Thus, the search does not start with a plain alphabeta window [-INF_SCORE, +INF_SCORE], but with a reduce window [-1, +1] that will just find who is the winner. In case the game outcome is a draw, the search will stop here otherwise another search with a [+1, +8] window for the winner side will start. If the winning score falls within these bounds, the search is stopped else it is restarted with a last window of [+8, +64]. The search is then made within the PVS_root function.
Parameters
board board to solve.
hash_table hash table to memorize the analysis.
mode search mode: exact or win/draw/loss.
bestmove the bestmove found.
{
    int score, bound;
    MoveList movelist[MAX_MOVE + 2];
    board->n_nodes = 0;
    board_get_movelist(board, movelist);
    if (movelist->next != NULL) { /* normal play ? */
        if (board->n_empties > EMPTIES_DEEP_TO_SHALLOW_SEARCH)
            movelist_sort_fastfirst(movelist, board);
        PVS_root(board, hash_table, -1, +1, depth, movelist);
        *bestmove = movelist->next->move;
    } else { /* pass ? */
        bestmove->n = 0;
        board_update_pass(board);
        board_get_movelist(board, movelist);
        if (movelist->next == NULL) { /* game over ? */
            bestmove->score = board_get_final_score(board);
            *bestmove->position = NOMOVE;
        } else {
            if (board->n_empties > EMPTIES_DEEP_TO_SHALLOW_SEARCH)
                movelist_sort_fastfirst(movelist, board);
            PVS_root(board, hash_table, -1, +1, depth - 1, movelist);
            bestmove->score = -movelist->next->move.score;
            *bestmove->position = PASS;
        }
        board_restore_pass(board);
    }
}
References board_get_final_score(), board_get_movelist(), board_restore_pass(), board_update_pass(), EMPTIES_DEEP_TO_SHALLOW_SEARCH, MAX_MOVE, MoveList::move, movelist_sort_fastfirst(), Move::n, Board::n_empties, Board::n_nodes, MoveList::next, NOMOVE, PASS, Move::position, PVS_root(), and Move::score.
Referenced by main().
usage()
void usage (void)
Print program usage.
Explain the program command line parameters.
{
    fprintf(stderr,"solver [options] <script_file>\n");
    fprintf(stderr,"\nSolve a set of othello engdame problems\n");
    fprintf(stderr,"\nOptions:\n");
    fprintf(stderr,"  -v            verbose mode.\n");
    fprintf(stderr,"  -vv           very verbose mode.\n");
    fprintf(stderr,"  -h <nbits>    set hash table size.\n");
    fprintf(stderr,"\nExample:\n");
    fprintf(stderr,"solver -v -h 20 fforum-20-39.scr\n\n");
    exit(EXIT_FAILURE);
}
Referenced by main().
Variable Documentation
FLIPPING_DIRECTION_ID
const int FLIPPING_DIRECTION_ID[BOARD_SIZE]
Initial value:
= {
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 1, 2, 2, 2, 2, 3, 3,
    0, 1, 1, 2, 2, 2, 2, 3, 3,
    0, 4, 4, 5, 5, 5, 5, 6, 6,
    0, 4, 4, 5, 5, 5, 5, 6, 6,
    0, 4, 4, 5, 5, 5, 5, 6, 6,
    0, 4, 4, 5, 5, 5, 5, 6, 6,
    0, 7, 7, 8, 8, 8, 8, 9, 9,
    0, 7, 7, 8, 8, 8, 8, 9, 9,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0
}
a flipping direction ID for each square
Referenced by board_check_move(), board_count_flips(), board_do_flip(), and board_get_move().
QUADRANT_ID
const int QUADRANT_ID[BOARD_SIZE]
Initial value:
= {
    4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 0, 0, 0, 0, 1, 1, 1, 1,
    4, 0, 0, 0, 0, 1, 1, 1, 1,
    4, 0, 0, 0, 0, 1, 1, 1, 1,
    4, 0, 0, 0, 0, 1, 1, 1, 1,
    4, 2, 2, 2, 2, 3, 3, 3, 3,
    4, 2, 2, 2, 2, 3, 3, 3, 3,
    4, 2, 2, 2, 2, 3, 3, 3, 3,
    4, 2, 2, 2, 2, 3, 3, 3, 3,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4
}
a quadrant id for each square
Referenced by alphabeta_shallow(), and board_set().